package me.joshh.reportsystem.commands.cmds;

import me.joshh.reportsystem.ReportSystem;
import me.joshh.reportsystem.functions.Report;
import org.bukkit.Bukkit;
import org.bukkit.ChatColor;
import org.bukkit.Material;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.bukkit.inventory.Inventory;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.BookMeta;
import org.bukkit.inventory.meta.ItemMeta;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

public class ActiveReportsCommand implements CommandExecutor {

    // chatgpt is a fucking livesaver
    // this code was generated by chatgpt and it actually workst

    public static HashMap<String, List<Report>> activeReports = ReportSystem.activeReports;


    @Override
    public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
        if(sender instanceof Player) {
            Player p = (Player) sender;
            if (p.hasPermission("rs.manage")) {
                Inventory reportInventory = Bukkit.createInventory(p, 54, "Active Reports");

                ItemStack grayGlass = new ItemStack(Material.STAINED_GLASS_PANE, 1, (short) 7);
                ItemMeta glassMeta = grayGlass.getItemMeta();
                glassMeta.setDisplayName(" ");
                grayGlass.setItemMeta(glassMeta);
                for (int i = 0; i < 54; i++) {
                    if (i < 9 || i > 44 || i % 9 == 0 || (i + 1) % 9 == 0) {
                        reportInventory.setItem(i, grayGlass);
                    }
                }

                // Add the reports to the inventory
                int slot = 10;
                for (String player : activeReports.keySet()) {
                    ItemStack book = new ItemStack(Material.BOOK_AND_QUILL);
                    ItemMeta meta = book.getItemMeta();
                    meta.setDisplayName(ChatColor.GRAY + player);
                    List<String> lore = new ArrayList<>();
                    for (Report report : activeReports.get(player)) {
                        lore.add("§7"+report.getReporter().getName() + ": " + report.getReason() + " (" + report.getDate() + ")");
                    }
                    meta.setLore(lore);
                    book.setItemMeta(meta);
                    reportInventory.setItem(slot, book);
                    slot++;
                }

                p.openInventory(reportInventory);
            }
        }
        return false;
    }






}
